apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-administration-ui
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}-administration-ui
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-administration-ui
    spec:
      containers:
        - image: "{{ .Values.frontend.administration.image.repository }}:{{ .Values.frontend.administration.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.administration.image.pullPolicy }}
          name: {{ template "name" . }}-administration-ui
          ports:
            - containerPort: {{ .Values.frontend.administration.port }}
          volumeMounts:
            - name: config-prod
              mountPath: /usr/share/nginx/html/assets/config-ee.json
              subPath: config-ee.json
          readinessProbe:
{{ toYaml .Values.frontend.administration.readinessProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.frontend.administration.livenessProbe | indent 12 }}
      volumes:
        - name: config-ee
          configMap:
            name: "{{ template "name" . }}-administration-ui"