---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-backend
  labels:
    app: {{ template "name" . }}-backend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "name" . }}-backend
{{- if .Values.backend.service.clusterIP }}
  clusterIP: {{ .Values.backend.service.clusterIP }}
{{- end }}
{{- if .Values.backend.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.backend.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.backend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.backend.service.loadBalancerIP }}
{{- end }}
{{- if .Values.backend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.backend.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: 8090
      protocol: TCP
    {{- if .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
    {{- end }}
  type: "{{ .Values.backend.service.type }}"