{{- if .Values.backend.enabled }}
{{- if .Values.backend.licenseFile }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-backend-license
  labels:
    app: {{ template "name" . }}-backend-license
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  license.l4j: |
{{ .Values.backend.licenseFile | indent 4 -}}
{{- end }}
{{- end }}