apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-gatling-ui
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}-gatling-ui
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-gatling-ui
    spec:
{{- if .Values.frontend.gatling.affinity }}
      affinity:
{{ toYaml .Values.frontend.gatling.affinity | indent 8 }}
{{- end }}
{{- if .Values.frontend.gatling.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.frontend.gatling.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - image: "{{ .Values.frontend.gatling.image.repository }}:{{ .Values.frontend.gatling.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.gatling.image.pullPolicy }}
          name: {{ template "name" . }}-gatling-ui
          ports:
            - containerPort: {{ .Values.frontend.gatling.port }}
          volumeMounts:
            - name: config-prod
              mountPath: /usr/share/nginx/html/assets/config-prod.json
              subPath: config-prod.json
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.gatling.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.gatling.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config-prod
          configMap:
            name: "{{ template "name" . }}-gatling-ui"