{{- if .Values.frontendBeta.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-frontend-beta-env
  labels:
    app: {{ template "name" . }}-frontend-beta-env
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{- range $key, $value := .Values.frontendBeta.env }}
  {{ $key }}: {{ quote $value -}}
{{- end }}
{{- end }}