apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-documentation
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}-documentation
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-documentation
    spec:
{{- if .Values.documentation.affinity }}
      affinity:
{{ toYaml .Values.documentation.affinity | indent 8 }}
{{- end }}
{{- if .Values.documentation.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.documentation.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - image: "{{ .Values.documentation.image.repository }}:{{ .Values.documentation.image.tag }}"
          imagePullPolicy: {{ .Values.documentation.image.pullPolicy }}
          name: {{ template "name" . }}-documentation
          ports:
            - containerPort: {{ .Values.documentation.port }}



