apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}-keycloak
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ (.Files.Glob "keycloak/*").AsSecrets | indent 2 }}