{{- if .Values.frontend.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-frontend
  labels:
    app: {{ template "name" . }}-frontend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.frontend.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-frontend
    spec:
    {{- if .Values.frontend.schedulerName }}
      schedulerName: "{{ .Values.frontend.schedulerName }}"
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
    {{- if .Values.frontend.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.frontend.nodeSelector | indent 2 }}
    {{- end }}
    {{- if .Values.frontend.securityContext }}
      securityContext:
      {{ toYaml .Values.frontend.securityContext | indent 2 }}
    {{- end }}
    {{- if .Values.frontend.tolerations }}
      tolerations:
      {{ toYaml .Values.frontend.tolerations | indent 2 }}
    {{- end }}
    {{- if .Values.frontend.affinity }}
      affinity:
      {{ toYaml .Values.frontend.affinity | indent 2 }}
    {{- end }}
      volumes:
      - name: config-ee
        configMap:
          name: "{{ template "name" . }}-frontend-config"
      - name: nginx-template
        configMap:
          name: "{{ template "name" . }}-frontend-nginx"
      containers:
      - name: {{ template "name" . }}-frontend
        image: "{{ .Values.registry }}/{{ .Values.frontend.image }}:{{ .Values.version }}"
        imagePullPolicy: {{ quote .Values.imagePullPolicy }}
        env:
          - name: NGINX_PORT
            value: "{{ .Values.frontend.port }}"
        ports:
          - name: http-port
            containerPort: {{ .Values.frontend.port }}
        volumeMounts:
          - name: config-ee
            mountPath: /usr/share/nginx/html/app/config-ee.json
            subPath: config-ee.json
          - name: nginx-template
            mountPath: /etc/nginx/templates/default.conf.template
            subPath: default.conf.template
        readinessProbe:
{{ toYaml .Values.frontend.readinessProbe | indent 10 }}
        livenessProbe:
{{ toYaml .Values.frontend.livenessProbe | indent 10 }}
{{- end }}