{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-frontend-nginx
  labels:
    app: {{ template "name" . }}-frontend-nginx
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  default.conf.template: |-
    server {
        listen       ${NGINX_PORT};
        listen  [::]:${NGINX_PORT};
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
{{- end }}