{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-frontend
  labels:
    app: {{ template "name" . }}-frontend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: "{{ template "name" . }}-frontend"
  clusterIP: None
  ports:
  - name: http
    port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
{{- end }}