apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-storage
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}-storage
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-storage
    spec:
      containers:
        - image: "{{ .Values.backend.storage.image.repository }}:{{ .Values.backend.storage.image.tag }}"
          imagePullPolicy: {{ .Values.backend.storage.image.pullPolicy }}
          name: {{ template "name" . }}-storage
          ports:
            - containerPort: {{ .Values.backend.storage.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SERVER_PORT
              value: "{{ .Values.backend.storage.port }}"
          volumeMounts:
            - mountPath: "/home/kraken/data"
              name: storage-data
      volumes:
        - name: storage-data
          persistentVolumeClaim:
            claimName: storage-data


