---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-project-ui
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{- range $path, $config := .Values.frontend.project.config }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end }}