apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-runtime
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}-runtime
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-runtime
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "name" . }}-runtime
      {{- end }}
      containers:
        - image: "{{ .Values.backend.runtime.image.repository }}:{{ .Values.backend.runtime.image.tag }}"
          imagePullPolicy: {{ .Values.backend.runtime.image.pullPolicy }}
          name: {{ template "name" . }}-runtime
          ports:
            - containerPort: {{ .Values.backend.runtime.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SERVER_PORT
              value: "{{ .Values.backend.runtime.port }}"
            - name: KRAKEN_GRAFANA_URL
              value: "http://{{ .Values.grafana.fullnameOverride }}:{{ .Values.grafana.service.port }}"
            - name: KRAKEN_INFLUXDB_URL
              value: "http://{{ .Values.influxdb.fullnameOverride }}:{{ .Values.influxdb.config.http.bind_address }}"
            - name: KRAKEN_STORAGE_URL
              value: "http://{{ template "name" . }}-storage:{{ .Values.backend.storage.port }}"
            - name: KRAKEN_ANALYSIS_URL
              value: "http://{{ template "name" . }}-analysis:{{ .Values.backend.analysis.port }}"
            - name: KRAKEN_RUNTIME_URL
              value: "http://{{ template "name" . }}-runtime:{{ .Values.backend.runtime.port }}"
            - name: KRAKEN_K8S_PATCHHOSTS
              value: "{{ .Values.backend.runtime.k8s.patchHosts }}"
            - name: KRAKEN_K8S_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: KRAKEN_VERSION
              value: "{{ .Values.backend.runtime.image.tag }}"
          {{- if .Values.backend.licenseFile }}
          volumeMounts:
            - name: license-l4j
              mountPath: "/home/kraken/data/license.l4j"
              subPath: "license.l4j"
          {{- end }}
      {{- if .Values.backend.licenseFile }}
      volumes:
        - name: license-l4j
          configMap:
            name: "{{ template "name" . }}-backend-license"
      {{- end }}