apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.yml: |
    {{- toYaml .Values.config | nindent 4 }}
