apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

spec:
  replicas: {{ .Values.replicas }}
  strategy: {{ toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets: {{ toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.extraInitContainers }}
      initContainers: {{ tpl .Values.extraInitContainers . | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes: {{ toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        env:
        - name: OCTOPERF_KUBERNETES_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: AGENT_TOKEN
          value: {{ default "" .Values.token | quote }}
        - name: SERVER_URL
          value: {{ default "https://api.octoperf.com" .Values.serverUrl | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- if .Values.image.debug }}
        - name: JAVA_OPTS
          value: "-Dorg.slf4j.simpleLogger.defaultLogLevel=debug"
        {{- end }}
        {{- if .Values.extraEnvVars }}
        {{ tpl .Values.extraEnvVars . | nindent 8 }}
        {{- end }}
        {{- if .Values.volumeMounts }}
        volumeMounts: {{ tpl .Values.volumeMounts . | nindent 10 }}
        {{- end }}