{{- if .Values.utilityServer.enabled }}
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "name" . }}-ingress-utility-server-legacy
  labels:
    app: {{ template "name" . }}-ingress-utility-server-legacy
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- with .Values.ingress.annotations }}
  {{ toYaml . | indent 2 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- $dot := . }}
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /utilities
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-utility-server
              port: 
                number: {{ $dot.Values.utilityServer.port }}
  {{- end }}
{{- end }}
{{- end }}