{{- if .Values.frontendLegacy.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-frontend-legacy
  labels:
    app: {{ template "name" . }}-frontend-legacy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- with .Values.frontendLegacy.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontendLegacy.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-frontend-legacy
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-frontend-legacy
    spec:
    {{- if .Values.frontendLegacy.schedulerName }}
      schedulerName: "{{ .Values.frontendLegacy.schedulerName }}"
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
    {{- if .Values.frontendLegacy.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.frontendLegacy.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.frontendLegacy.securityContext }}
      securityContext:
      {{ toYaml .Values.frontendLegacy.securityContext | nindent 8 }}
    {{- end }}
    {{- if .Values.frontendLegacy.tolerations }}
      tolerations:
      {{ toYaml .Values.frontendLegacy.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.frontendLegacy.affinity }}
      affinity:
      {{ toYaml .Values.frontendLegacy.affinity | nindent 8 }}
    {{- end }}
      volumes:
      - name: config-ee
        configMap:
          name: "{{ template "name" . }}-frontend-legacy-config"
      containers:
      - name: {{ template "name" . }}-frontend-legacy
        image: "{{ .Values.registry }}/{{ .Values.frontendLegacy.image }}:{{ .Values.version }}"
        imagePullPolicy: {{ quote .Values.imagePullPolicy }}
        env:
          - name: "NGINX_PORT"
            value: "{{ .Values.frontendLegacy.port }}"
        ports:
          - name: http-port
            containerPort: {{ .Values.frontendLegacy.port }}
        volumeMounts:
          - name: config-ee
            mountPath: /usr/share/nginx/html/config-ee.json
            subPath: config-ee.json
        readinessProbe:
        {{ toYaml .Values.frontendLegacy.readinessProbe | nindent 10 }}
        livenessProbe:
        {{ toYaml .Values.frontendLegacy.livenessProbe | nindent 10 }}
{{- end }}