{{- if .Values.frontendLegacy.enabled }}
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "name" . }}-ingress-frontend-legacy
  labels:
    app: {{ template "name" . }}-ingress-frontend-legacy
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- $dot := . }}
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /app(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-frontend-legacy
              port: 
                number: {{ $dot.Values.frontendLegacy.port }}
  {{- end }}
{{- end }}
{{- end }}