{{- if .Values.frontendLegacy.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-frontend-legacy
  labels:
    app: {{ template "name" . }}-frontend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: "{{ template "name" . }}-frontend-legacy"
  clusterIP: None
  ports:
  - name: http
    port: {{ .Values.frontendLegacy.port }}
    targetPort: {{ .Values.frontendLegacy.port }}
    protocol: TCP
{{- end }}