{{- if .Values.doc.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-doc
  labels:
    app: {{ template "name" . }}-doc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.doc.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.doc.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-doc
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-doc
    spec:
    {{- if .Values.doc.schedulerName }}
      schedulerName: "{{ .Values.doc.schedulerName }}"
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.doc.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.doc.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.doc.securityContext }}
      securityContext:
      {{- toYaml .Values.doc.securityContext | nindent 8 }}
    {{- end }}
    {{- if .Values.doc.tolerations }}
      tolerations:
      {{- toYaml .Values.doc.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.doc.affinity }}
      affinity:
      {{- toYaml .Values.doc.affinity | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ template "name" . }}-doc
        image: "{{ .Values.registry }}/{{ .Values.doc.image }}:{{ .Values.version }}"
        imagePullPolicy: {{ quote .Values.imagePullPolicy }}
        env:
        - name: "NGINX_PORT"
          value: "{{ .Values.doc.port }}"
        ports:
        - name: http-port
          containerPort: {{ .Values.doc.port }}
        readinessProbe:
        {{- toYaml .Values.doc.readinessProbe | nindent 10 }}
        livenessProbe:
        {{- toYaml .Values.doc.livenessProbe | nindent 10 }}
{{- end }}
