{{- if .Values.doc.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-doc
  labels:
    app: {{ template "name" . }}-doc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.doc.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.doc.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-doc
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-doc
    spec:
    {{- if .Values.doc.schedulerName }}
      schedulerName: "{{ .Values.doc.schedulerName }}"
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
    {{- if .Values.doc.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.doc.nodeSelector | indent 2 }}
    {{- end }}
    {{- if .Values.doc.securityContext }}
      securityContext:
      {{ toYaml .Values.doc.securityContext | indent 2 }}
    {{- end }}
    {{- if .Values.doc.tolerations }}
      tolerations:
      {{ toYaml .Values.doc.tolerations | indent 2 }}
    {{- end }}
    {{- if .Values.doc.affinity }}
      affinity:
      {{ toYaml .Values.doc.affinity | indent 2 }}
    {{- end }}
      containers:
      - name: {{ template "name" . }}-doc
        image: "{{ .Values.registry }}/{{ .Values.doc.image }}:{{ .Values.version }}"
        env:
        - name: NGINX_PORT
          value: "{{ .Values.frontendLegacy.port }}"
        ports:
        - name: http-port
          containerPort: {{ .Values.doc.port }}
        readinessProbe:
        {{ toYaml .Values.doc.readinessProbe | indent 2 }}
        livenessProbe:
        {{ toYaml .Values.doc.livenessProbe | indent 2 }}
{{- end }}