{{- if .Values.doc.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-doc
  labels:
    app: {{ template "name" . }}-doc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: "{{ template "name" . }}-doc"
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
{{- end }}