{{- if .Values.doc.enabled }}
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "name" . }}-ingress-doc
  labels:
    app: {{ template "name" . }}-ingress-doc
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^([^.?]*[^/])$ $1/ redirect;
  {{- with .Values.ingress.annotations }}
  {{ toYaml . | indent 2 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- $dot := . }}
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /doc(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-doc
              port: 
                number: {{ $dot.Values.doc.port }}
  {{- end }}
{{- end }}
{{- end }}