{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "name" . }}-ingress
  labels:
    app: {{ template "name" . }}-ingress
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  {{- with .Values.ingress.annotations }}
  {{ toYaml . | indent 2 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- $dot := . }}
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- if $dot.Values.frontendLegacy.enabled }}
        - path: /app(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-frontend
              port: 
                number: {{ $dot.Values.frontendLegacy.port }}
        {{- end }}
        {{- if $dot.Values.frontend.enabled }}
        - path: /ui(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-frontend-beta
              port: 
                number: {{ $dot.Values.frontend.port }}
        {{- end }}
        {{- if $dot.Values.doc.enabled }}
        - path: /doc(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-doc
              port: 
                number: {{ $dot.Values.doc.port }}
        {{- end }}
        - path: (/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-backend
              port: 
                number: {{ $dot.Values.backend.port }}
  {{- end }}
{{- end }}