{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "name" . }}-ingress
  labels:
    app: {{ template "name" . }}-ingress
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- $dot := . }}
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- if $dot.Values.frontend.enabled }}
        - path: /app
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-frontend
              port: 
                number: 80
        {{- end }}
        {{- if $dot.Values.doc.enabled }}
        - path: /doc
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-doc
              port: 
                number: 80
        {{- end }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "name" $dot }}-backend
              port: 
                number: 8090
  {{- end }}
{{- end }}