{{ if and (.Values.backend.persistentVolume.storageClassName) (eq .Values.backend.persistentVolume.storageClassName "local-storage") }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  labels:
    app: {{ template "name" . }}-storage-class
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{ end }}