---

elasticsearch:
  enabled: false
  esJavaOpts: "-Xmx1g -Xms1g"
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 4Gi

backend:
  enabled: true
  env:
    SERVER_HOSTNAME: 192.168.49.1.xip.io

frontend:
  enabled: true

frontendBeta:
  enabled: true

doc:
  enabled: true

ingress:
  enabled: true
  hosts:
    - 192.168.49.1.xip.io
