---

elasticsearch:
  enabled: true
  esJavaOpts: "-Xmx1g -Xms1g"
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 4Gi

doc:
  enabled: false

utilityServer:
  enabled: false

mcpServer:
  enabled: true
  applicationYml: |-
    server:
      hostname: 127.0.0.1.sslip.io
      public:
        port: 80

backend:
  applicationYml: |-
    server:
      hostname: 127.0.0.1.sslip.io
      public:
        port: 80
    elasticsearch:
      hostname: elasticsearch-master-headless
      # Must match elasticsearch password
      password: "0ct0P3rf"

ingress:
  enabled: true
  hosts:
    - 127.0.0.1.sslip.io
