---

elasticsearch:
  esJavaOpts: "-Xmx1g -Xms1g"
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 4Gi

postgresql:
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 1Gi

ingress:
  enabled: true

backend:
  env:
    DEBUG: "true"
  applicationYml: |-
    server:
      public:
        port: 80
    elasticsearch:
      hostname: elasticsearch-master-headless
    spring:
      datasource:
        url: "jdbc:postgresql://enterprise-edition-postgresql-hl/postgres"