---

elasticsearch:
  enabled: true
  esJavaOpts: "-Xmx1g -Xms1g"
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 4Gi

backend:
  env:
    SERVER_HOSTNAME: 192.168.49.2.sslip.io

ingress:
  enabled: true
  hosts:
    - 192.168.49.2.sslip.io
