---

elasticsearch:
  esJavaOpts: "-Xmx1g -Xms1g"
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 4Gi

postgresql:
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 1Gi

backend:
  env:
    SERVER_HOSTNAME: 192.168.49.2.xip.io

ingress:
  hosts:
    - 192.168.49.2.xip.io