---

elasticsearch:
  esJavaOpts: "-Xmx1g -Xms1g"
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 4Gi

postgresql:
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 1Gi

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
  - "localhost"

backend:
    # config/application.yml
  applicationYml: |-
    server:
      hostname: "localhost"
      public:
        port: 80
    elasticsearch:
      hostname: "elasticsearch-master-headless"