kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-data
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.backend.storage.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.backend.storage.persistence.size | quote }}
  {{- if .Values.backend.storage.persistence.storageClass }}
  {{- if (eq "-" .Values.backend.storage.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.backend.storage.persistence.storageClass }}"
  {{- end }}
  {{- end }}