{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.backend.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "name" . }}-backend
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
{{- with .Values.backend.ingress.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ template "name" . }}-backend
              servicePort: {{ .Values.backend.service.port }}
            path: {{ .Values.backend.ingress.path }}
      host: {{ .Values.host.name }}
{{- end }}